server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_manager_db
    username: dev
    password: 321123
    initialization-mode: always
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    jdbc:
      dialect: postgresql

api:
  security:
    token:
      secret: PQo4bGtHYgDAvf4AIy853ZnZuItchyQb